---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: webapp
  namespace: flux-system
spec:
  interval: 30s
  path: ./k8s/001
  prune: true
  sourceRef:
    kind: GitRepository
    name: crounchynerd
  targetNamespace: staging

